### ISSUE TITLE
OCP\IUserManager but this class was not found.

### ISSUE THREAD

**Issue by mmetlicraft** [nextcloud-deps/ocp#15]
Good day 

I need help, I have the below constructor and I having error argument \"$userManager\" of method \"__construct()\" has type \"OCP\\IUserManager\" but this class was not found.",

public function __construct(private readonly IUserManager $userManager, private readonly IAccountManager $accountManager)
{
}

I have "nextcloud/ocp": "^27.0", in my composer.json and use OCP\IUserManager in my class;

How can I resolve the error? I'm using symfony for development.

Thanks in advance

**Comment by nickvergessen** [comment]
This is not meant to be used to produce code. It only helps as a "type resolver" in static code analysis like Psalm and PHPStan.
Code injection as you posted above should never the less work, but if not, make sure you are within the context of a Nextcloud app.
